### ISSUE TITLE
Issue with IPlocation

### ISSUE THREAD

**Issue by nicothed** [kolonist/node-xwhois#2]
This module looks amazing, but I get the following error after calling your exact code:
{ Error: ENOENT: no such file or directory, open 'test/GeoIP/IP2LOCATION-LITE-DB5.IPV6.BIN'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'test/GeoIP/IP2LOCATION-LITE-DB5.IPV6.BIN' }

**Comment by kolonist** [comment]
You probably don't have IP2Location BD files. You can download it for free at https://www.ip2location.com/
